// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBajUsMYIDv_vMgezpbu4ieNdG5QaQN_c',
    appId: '1:429718866870:web:2a760dcb5b500d2daccf17',
    messagingSenderId: '429718866870',
    projectId: 'pos-kasir-3b69b',
    authDomain: 'pos-kasir-3b69b.firebaseapp.com',
    storageBucket: 'pos-kasir-3b69b.firebasestorage.app',
    measurementId: 'G-K024RZ48CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qXl0wixk7ZUBkFPT8w2YTii_YzpixGw',
    appId: '1:429718866870:android:badfdf44040c430aaccf17',
    messagingSenderId: '429718866870',
    projectId: 'pos-kasir-3b69b',
    storageBucket: 'pos-kasir-3b69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIvwLc92zcXyrNwacR3Od1qYQZaNyl-0',
    appId: '1:429718866870:ios:fe87f4cd14a8cb17accf17',
    messagingSenderId: '429718866870',
    projectId: 'pos-kasir-3b69b',
    storageBucket: 'pos-kasir-3b69b.firebasestorage.app',
    iosBundleId: 'com.example.posMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxIvwLc92zcXyrNwacR3Od1qYQZaNyl-0',
    appId: '1:429718866870:ios:fe87f4cd14a8cb17accf17',
    messagingSenderId: '429718866870',
    projectId: 'pos-kasir-3b69b',
    storageBucket: 'pos-kasir-3b69b.firebasestorage.app',
    iosBundleId: 'com.example.posMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBa-7obOq1go8b4DPEmy_SZG9TwWnY1IU',
    appId: '1:429718866870:web:70054dba224ae73daccf17',
    messagingSenderId: '429718866870',
    projectId: 'pos-kasir-3b69b',
    authDomain: 'pos-kasir-3b69b.firebaseapp.com',
    storageBucket: 'pos-kasir-3b69b.firebasestorage.app',
    measurementId: 'G-9WQY0WXDTQ',
  );
}
